name: Build Theme Artifacts
run-name: ${{ github.actor }} is building Decanter 🛠️
on: [push]
jobs:
  Build-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm
        uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
