name: Test Theme
run-name: Running visual tests 👓
on: [push]
permissions:
  contents: write
jobs:
  Capture-Reference:
    runs-on: ubuntu-latest
    steps:
      - name: Execute backstop reference
        run: |
          docker-compose run backstop reference --config=/config.js
      - name: Commit results
        run: |
          if ! git diff-index --quiet HEAD; then
            git config --global user.name '${{ github.actor }}'
            git config --global user.email '${{ github.actor }}@users.noreply.github.com'
            git commit -am "Automated artifact build by Github Actions"
            git push
          fi
